### ISSUE TITLE
Break apps using has-many

### ISSUE THREAD

**Issue by Luiz-N** [rmmmp/emberfire-utils#29]
I like a lot of the features/ideas here but does this completely break any attempt at a `has-many` relationship? Would it be possible to make it optional or backwards compatible?

**Comment by rmmmp** [comment]
If you're using the emberfire adapter then the `hasMany` should work. 

However, I'm in the process of rolling out my own adapter with some benefits than emberfire. Currently that doesn't support`hasMany` because it goes against what I'm trying to accomplish of lazily loading it (no ids will be downloaded) and infinite scrolling. 

The reason fhat I haven't merged it yet because I'm still looking for ways to support `hasMany` with those usage. I just haven't had to time to work on it yet.

**Comment by rmmmp** [comment]
`hasMany` is now supported in the `firebase-flex` adapter
